# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{crawler}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tyler Cunnion"]
  s.date = %q{2010-01-25}
  s.default_executable = %q{crawler}
  s.description = %q{BFS webcrawler that implements Observable}
  s.email = %q{tyler.cunnion@gmail.com}
  s.executables = ["crawler"]
  s.files = [
    ".gitignore",
     "VERSION",
     "bin/crawler",
     "lib/crawler.rb",
     "lib/crawler/observer.rb",
     "lib/crawler/webcrawler.rb",
     "spec/crawler/crawler_spec.rb",
     "spec/crawler/observer_spec.rb",
     "spec/fixtures/excluded/shouldnt-hit.html",
     "spec/fixtures/exclusion.html",
     "spec/fixtures/external.html",
     "spec/fixtures/index.html",
     "spec/fixtures/messed-up.html",
     "spec/fixtures/non-html.html",
     "spec/fixtures/non-http.html",
     "spec/fixtures/page2.html",
     "spec/fixtures/page3.html",
     "spec/fixtures/page4.html",
     "spec/fixtures/page5.html",
     "spec/fixtures/pdf.pdf",
     "spec/fixtures/self-reference.html",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/tylercunnion/crawler}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple webcrawler}
  s.test_files = [
    "spec/crawler/crawler_spec.rb",
     "spec/crawler/observer_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

